default_platform(:ios)

platform :ios do

  desc "Run unit tests"
  lane :test do
    scan(
      scheme: "MutipleFrameworkApp",
      clean: true
    )
  end

  desc "Build app without signing"
  lane :build do
    build_app(
      scheme: "MutipleFrameworkApp",
      export_method: "development",
      skip_package_ipa: true,
      skip_codesigning: true
    )
  end

 desc "Run tests and then build"
  lane :local_setup do
    test
    build
  end

end